### ISSUE TITLE
npm install --save taro-cropper

### ISSUE THREAD

**Issue by SuperIron** [SunnyQjm/taro-cropper#1]
安装报错了~

Maximum call stack size exceeded

**Comment by SunnyQjm** [comment]
@SuperIron 这个应该不是这个组件库的问题，你可以尝试删除node_modeules, 然后重新安装依赖。不行的话先升级npm版本到最新，再删除node_modeules，重新安装依赖。

**Comment by SuperIron** [comment]
好的 我试试 谢谢大佬



------------------ 原始邮件 ------------------
发件人: "SunnyQjm"<notifications@github.com>; 
发送时间: 2019年9月1日(星期天) 中午11:23
收件人: "SunnyQjm/taro-cropper"<taro-cropper@noreply.github.com>; 
抄送: "倪铁林"<58218596@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [SunnyQjm/taro-cropper] npm install --save taro-cropper (#1)




@SuperIron 这个应该不是这个组件库的问题，你可以尝试删除node_modeules, 然后重新安装依赖。不行的话先升级npm版本到最新，再删除node_modeules，重新安装依赖。
