### ISSUE TITLE
小程序Audits 发现6个废弃api

### ISSUE THREAD

**Issue by newbaner** [SunnyQjm/taro-cropper#13]
> 使用即将废弃或已废弃接口，可能导致小程序运行不正常。一般而言，接口不会立即去掉，但保险起见，建议不要使用，避免后续小程序突然运行异常。
 
taro-cropper：version 1.0.9
微信开发者工具版本：1.02.1911180
调试基础库: 2.9.4

![image](https://user-images.githubusercontent.com/26630929/71541850-f7105800-2999-11ea-9b07-49bd6a773a1d.png)

**Comment by SunnyQjm** [comment]
https://github.com/SunnyQjm/taro-cropper/commit/d657e7caee48fac7096f32219ae32d34ae53442c fix
