### ISSUE TITLE
taro版本3.X   taro-cropper@react   TaroCropperComponent报错

### ISSUE THREAD

**Issue by lightShowers** [SunnyQjm/taro-cropper#22]
![1600677840(1)](https://user-images.githubusercontent.com/46345829/93750815-af6be380-fc2e-11ea-8b85-f2399f2d7b31.png)

**Comment by lightShowers** [comment]
![1600680131(1)](https://user-images.githubusercontent.com/46345829/93751048-0b366c80-fc2f-11ea-8f17-b25f5e29f586.jpg)
catTaroCropper = (node) => {
		console.log(node)//打印出来null
		this.taroCropper = node;
	}

**Comment by shenghanqin** [comment]
@lightShowers 你这是h5上的吧？我前几个月就发现小程序版本没啥问题，h5上一直有问题的。

**Comment by lightShowers** [comment]
> @lightShowers 你这是h5上的吧？我前几个月就发现小程序版本没啥问题，h5上一直有问题的。

不是啊，我这就是微信小程序
![1600737541(1)](https://user-images.githubusercontent.com/46345829/93836255-b0475880-fcb4-11ea-9843-413451641e57.jpg)

**Comment by shenghanqin** [comment]
> > @lightShowers 你这是h5上的吧？我前几个月就发现小程序版本没啥问题，h5上一直有问题的。
> 
> 不是啊，我这就是微信小程序
> ![1600737541(1)](https://user-images.githubusercontent.com/46345829/93836255-b0475880-fcb4-11ea-9843-413451641e57.jpg)

升级一下微信开发者工具稳定版到最新版，0827版本是有问题的，0915没问题

**Comment by shenghanqin** [comment]
你跑一下h5版本，看问题大不大？

**Comment by shenghanqin** [comment]
> 你跑一下h5版本，看问题大不大？

@lightShowers 可以加我微信，交流一下 xiaoxili22
