### ISSUE TITLE
请问不通过自带的完成按钮，怎么调取onCut

### ISSUE THREAD

**Issue by hccici** [SunnyQjm/taro-cropper#6]
请问不通过自带的完成按钮，怎么调取onCut

**Comment by SunnyQjm** [comment]
通过 ref 获取 TaroCropper 对象的实例，然后调用该对象的cut方法，会返回一个Promise对象

**Comment by SunnyQjm** [comment]
@hccici

**Comment by SunnyQjm** [comment]
@hccici 
https://github.com/SunnyQjm/taro-cropper/blob/master/src/pages/index/index.tsx
这个实例里面有如何通过ref获得TaroCropper对象实例的例子，可以参考下
