### ISSUE TITLE
传入高度和宽度自适应问题

### ISSUE THREAD

**Issue by hccici** [SunnyQjm/taro-cropper#8]
描述：顶部和底部的显示是固定的，中间空白的地方放入这个taro-cropper组件，通过select('#id).boundingClientRect()，获取要填充部分的宽高，将此宽高可是传入taro-cropper之后，taro-cropper占据的位置比预测的小很多，请问这个自适应怎么处理，谢谢！

**Comment by SunnyQjm** [comment]
你用这种获得的宽高单位是px，taro-cropper要求传递的宽高是rpx。你可以自己换算一下，用taro.getSystemInfo可以获取到实际的宽度，实际宽度除750就是换算比例

**Comment by SunnyQjm** [comment]
@hccici
